version: '0.2'
import:
  - './cspell/sveltekit.yaml'
words:
  - basenames
  - baselining
  - dedup
  - elifecycle
  - hsts
  - idempotently
  - jgame
  - sameorigin
  - sonarlint
  - unstub
  - winget
ignorePaths: []
