import path from 'node:path'
import { EnvironmentError } from '#process/environment-error.js'

// Pure argument handling for `josh-app shot`: which routes were asked for, which viewport to use,
// and where each PNG lands. Kept separate from the orchestration in shot.ts and from the Playwright
// bridge in capture.ts so the exact contract — the one thing a caller reads back — is unit-testable
// without a build, a preview server or a browser (the same split dast.ts/zap.ts and load.ts/k6.ts
// use). See app-kit #200.

// A fixed directory rather than a flag: the route decides the file name, so the caller knows where
// an image will be before the run starts. `test-results` is already ignored by kit's distributed
// .gitignore (at any depth, no leading slash), so every consumer gets the ignore for free and no
// kit change is needed to add one.
//
// Playwright's default `outputDir` is also `test-results`, and Playwright clears it when a suite
// starts — so a later `josh-app verify` wipes these images. That is deliberate: they are throwaway
// verification artifacts regenerated by re-running the command, and sharing the directory keeps the
// project's generated-artifact surface at one entry instead of two.
const OUTPUT_DIR = path.join('test-results', 'screenshots')

const ROUTE_SEPARATOR = '/'

// Desktop is the default because that is the layout a review looks at first. Both are plain
// viewport sizes rather than Playwright device descriptors: a descriptor also brings a mobile user
// agent and touch emulation, which changes what the app serves — a screenshot command should show
// the same page at a different width, not a different page.
const DESKTOP_VIEWPORT: Viewport = { width: 1280, height: 800 }
const MOBILE_VIEWPORT: Viewport = { width: 390, height: 844 }

const MOBILE_FLAG = '--mobile'
// The slug suffix that keeps a mobile capture from overwriting the desktop one of the same route.
const MOBILE_SUFFIX = '-mobile'

// The slug for `/` — the one route whose path segments are empty, so it cannot name itself.
const ROOT_SLUG = 'root'

// Anything that is not a portable filename character is a separator, so a route with a query string
// or a non-ASCII segment still produces a path every OS accepts. Splitting on it — rather than
// replacing and then trimming the edges — is what keeps the leading and trailing runs from needing
// a second, backtracking-prone anchored pattern.
const UNSAFE_SLUG_PATTERN = /[^a-z0-9]+/iu

interface Viewport {
	width: number
	height: number
}

interface ShotRequest {
	route: string
	// Project-relative, so the printed path is the one the reader types.
	file: string
}

interface ShotPlan {
	requests: ReadonlyArray<ShotRequest>
	viewport: Viewport
	is_mobile: boolean
}

function usage_message(): string {
	return [
		'Usage: josh-app shot <route> [route...] [--mobile]',
		`Routes are absolute paths, e.g. josh-app shot ${ROUTE_SEPARATOR} ${ROUTE_SEPARATOR}blog`,
	].join('\n')
}

function invalid_route_message(route: string): string {
	return [
		`josh-app shot expects absolute routes, but received "${route}".`,
		`Prefix it with "${ROUTE_SEPARATOR}" — e.g. ${ROUTE_SEPARATOR}blog instead of blog.`,
	].join('\n')
}

// Flattening a route to a file name is not one-to-one: `/blog/post` and `/blog-post` both become
// blog-post.png. Capturing both in one run would silently overwrite one image and report BOTH as
// captured — the same silent success as photographing a 404 page. Refusing is the honest answer,
// and separate runs really do work: only the files a run is about to write are cleared, so the
// first route's image survives the second run.
function collision_message(file: string, routes: ReadonlyArray<string>): string {
	return [
		`josh-app shot cannot capture ${routes.join(' and ')} in one run:`,
		`both flatten to ${file}. Capture them in separate runs.`,
	].join('\n')
}

function is_present(part: string): boolean {
	return part !== ''
}

// A route is normalized by dropping empty segments, so `/blog/` and `/blog` name one file. `/`
// itself keeps its single slash — it is the route, not a trailing separator.
function normalize_route(route: string): string {
	const segments = route.split(ROUTE_SEPARATOR).filter((part) => is_present(part))

	return `${ROUTE_SEPARATOR}${segments.join(ROUTE_SEPARATOR)}`
}

function to_slug(route: string, is_mobile: boolean): string {
	const base = route.split(UNSAFE_SLUG_PATTERN).filter((part) => is_present(part))
	const name = base.length === 0 ? ROOT_SLUG : base.join('-').toLowerCase()

	return `${name}${is_mobile ? MOBILE_SUFFIX : ''}.png`
}

function to_output_path(route: string, is_mobile: boolean): string {
	return path.join(OUTPUT_DIR, to_slug(route, is_mobile))
}

function is_absolute_route(route: string): boolean {
	return route.startsWith(ROUTE_SEPARATOR)
}

// Duplicate routes collapse to one request: they would write the same file twice, and the second
// capture would only cost a page load. Two DIFFERENT routes landing on one file is a different
// thing entirely — see collision_message — and is rejected rather than collapsed.
function to_requests(routes: ReadonlyArray<string>, is_mobile: boolean): Array<ShotRequest> {
	const seen = new Set<string>()

	return routes.flatMap((route) => {
		const normalized = normalize_route(route)
		if (seen.has(normalized)) return []
		seen.add(normalized)

		return [{ route: normalized, file: to_output_path(normalized, is_mobile) }]
	})
}

function routes_by_file(requests: ReadonlyArray<ShotRequest>): Map<string, Array<string>> {
	const grouped = new Map<string, Array<string>>()

	for (const request of requests) {
		grouped.set(request.file, [...(grouped.get(request.file) ?? []), request.route])
	}

	return grouped
}

function assert_no_collision(requests: ReadonlyArray<ShotRequest>): void {
	const collision = [...routes_by_file(requests)].find(([, routes]) => routes.length > 1)
	if (collision === undefined) return

	throw new EnvironmentError(collision_message(collision[0], collision[1]))
}

// Turn the raw trailing argv into the plan the orchestrator executes. Throws on an empty route list
// or a relative route rather than returning an empty plan: a screenshot command that captured
// nothing and exited 0 is exactly the silent success app-kit #200 exists to remove.
//
// EnvironmentError, the same type `dast` raises for a stopped Docker daemon, because it buys the
// same presentation: a mistyped route is something the user fixes on the next line, so the CLI
// prints the message plainly and exits non-zero instead of dumping a stack trace at them.
function build_plan(argv: ReadonlyArray<string>): ShotPlan {
	const is_mobile = argv.includes(MOBILE_FLAG)
	const routes = argv.filter((argument) => argument !== MOBILE_FLAG)

	if (routes.length === 0) throw new EnvironmentError(usage_message())

	const invalid = routes.find((route) => !is_absolute_route(route))
	if (invalid !== undefined) throw new EnvironmentError(invalid_route_message(invalid))

	const requests = to_requests(routes, is_mobile)

	assert_no_collision(requests)

	return { requests, viewport: is_mobile ? MOBILE_VIEWPORT : DESKTOP_VIEWPORT, is_mobile }
}

const shot_routes = {
	OUTPUT_DIR,
	DESKTOP_VIEWPORT,
	MOBILE_VIEWPORT,
	MOBILE_FLAG,
	usage_message,
	invalid_route_message,
	normalize_route,
	to_output_path,
	build_plan,
}

export { shot_routes }
export type { ShotPlan, ShotRequest, Viewport }
