import { readFileSync } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'
import { describe, expect, it } from 'vitest'

const ENCODING = 'utf8'

// `josh sync` writes playwright.config.ts from a generator, and kit's own package-root copy is
// generated the same way, so the two agree byte for byte and the published file stands in for the
// generator — which kit does not export. A kit release that let its root copy drift from the
// generator would fail this too; the failure is loud and one `josh sync` diagnoses which of the two
// moved. ci.yml is deliberately excluded: it is a mapped file whose action pins are re-resolved at
// write time (kit#747), so the consumer copy legitimately differs from the template it came from.
const PLAYWRIGHT_CONFIG = 'playwright.config.ts'
const KIT_PLAYWRIGHT_CONFIG = path.join('node_modules', '@joshuafolkken', 'kit', PLAYWRIGHT_CONFIG)

function read_file(file_path: string): string {
	return readFileSync(file_path, ENCODING)
}

describe('kit-distributed playwright.config.ts', () => {
	it('matches the installed kit master, so a kit bump without a sync fails here', () => {
		// app-kit kept running kit 1.63.0's config through eleven kit releases, including the one
		// that made local `reuseExistingServer` opt-in (kit#784). Until then the local branch
		// reused whatever already listened on vite's default port, and — baseURL being derived
		// from that port — reported the whole suite green against a foreign application. The
		// stale copy was invisible because nothing compared it to the package it came from: the
		// dependency bump and the sync that must follow it were two steps, and only one had a
		// failing check behind it. See #168.
		expect(read_file(PLAYWRIGHT_CONFIG)).toBe(read_file(KIT_PLAYWRIGHT_CONFIG))
	})
})

const ROOT_TSCONFIG = 'tsconfig.json'

// Generated by `svelte-kit sync` and git-ignored, but `prepare:sync` regenerates it on every
// install, so it is on disk wherever this suite runs. read_excludes throws rather than returning
// an empty list when it is not, because a guard that silently stops comparing is the exact failure
// this file exists to prevent.
const GENERATED_TSCONFIG = path.join('.svelte-kit', ROOT_TSCONFIG)

// SvelteKit writes its exclusions relative to `.svelte-kit/`; the root config's are relative to the
// project root, so one leading `../` comes off before the two lists are comparable.
const PARENT_PREFIX = '../'

// `node_modules/**` and `node_modules` exclude the same files — TypeScript drops an excluded
// directory's whole subtree — so either spelling in the root config satisfies SvelteKit's glob.
const RECURSIVE_SUFFIX = '/**'

interface TsconfigExcludes {
	exclude?: ReadonlyArray<string>
}

function read_excludes(file_path: string): ReadonlyArray<string> {
	const result = ts.readConfigFile(file_path, (name) => ts.sys.readFile(name))
	if (result.error) throw new Error(`${file_path} is unreadable — run \`svelte-kit sync\``)

	const parsed: unknown = result.config
	const { exclude } = parsed as TsconfigExcludes
	if (!exclude) throw new Error(`${file_path} declares no exclude array`)

	return exclude
}

function to_root_relative(entry: string): string {
	return entry.startsWith(PARENT_PREFIX) ? entry.slice(PARENT_PREFIX.length) : entry
}

function is_covered(entry: string, root_excludes: ReadonlyArray<string>): boolean {
	if (root_excludes.includes(entry)) return true
	if (!entry.endsWith(RECURSIVE_SUFFIX)) return false

	return root_excludes.includes(entry.slice(0, -RECURSIVE_SUFFIX.length))
}

describe('kit-distributed root tsconfig.json', () => {
	it('keeps every exclusion SvelteKit generates, so a sync cannot drop the service worker', () => {
		// `exclude` does not merge across `extends` — a child's array replaces the parent's — so the
		// list `josh sync` writes into the root config silently discarded the six service-worker
		// globs `.svelte-kit/tsconfig.json` ships. SvelteKit excludes the service worker on purpose:
		// it runs in a worker context with its own `lib` and its own `$service-worker` ambient types,
		// so type-checking it under the app's config fails with no correct fix from inside that
		// config. Nothing compared the two lists, so the loss was invisible until a consumer added
		// `src/service-worker.ts`. See #167 and joshuafolkken/kit#796.
		const root_excludes = read_excludes(ROOT_TSCONFIG)
		const dropped = read_excludes(GENERATED_TSCONFIG)
			.map((entry) => to_root_relative(entry))
			.filter((entry) => !is_covered(entry, root_excludes))

		expect(dropped).toEqual([])
	})
})
